# Задаём имя проекта
name: megano-test

services:
    web:
        # Указываем директорию ./app, в которой содержится Dockerfile для сборки образа
        build: ./app
        # Запускаем встроенный сервер Django
        command: python manage.py runserver 0.0.0.0:8001
        # Пробрасываем 8000 порт контейнера на 8000 порт локалхоста(127.0.0.1:8000)
        ports:
            - 127.0.0.1:8001:8000
        # Файл содержащий переменные окружения для контейнера
        env_file:
            - .env
        # Дожидаемся запуска контейнера db
        depends_on:
            - db

    db:
        # Берём образ БД PostgreSQL версии 15
        image: postgres:16
        # Примонтируем том postgres-data к директории /var/lib/postgresql/data контейнера db
        volumes:
            - postgres-data:/var/lib/postgresql/data
        # Файл содержащий переменные окружения для контейнера
        env_file:
            - .env
        # Используем значения переменных окружения из .env файла
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}

volumes:
    # Объявляем том postgres-data для хранения данных PostgreSQL
    postgres-data:

