# Задаём имя проекта
name: megano-test

services:
    web:
        # Указываем директорию в которой содержится Dockerfile для сборки образа
        build:
          dockerfile: Dockerfile.prod
        # Запускаем встроенный сервер Django
        command: >
            sh -c "
            ls megano && gunicorn megano.wsgi:application --bind 0.0.0.0:8002
            "
        # Примонтируем том static-data к директории /home/app/web/static контейнера web
        volumes:
          - static-data:/home/app/web/static
        # Пробрасываем 8000 порт контейнера на 8000 порт локалхоста(127.0.0.1:8000)
        ports:
            - 127.0.0.1:8002:8002
        # Файл содержащий переменные окружения для контейнера
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        restart: always
        # Дожидаемся запуска контейнера db
        depends_on:
            - db
            - redis

    redis:
        image: "redis:alpine"
        container_name: redis
        ports:
            - "6380:6379"

    db:
        # Берём образ БД PostgreSQL версии 16
        image: postgres:16
        # Примонтируем том postgres-data к директории /var/lib/postgresql/data контейнера db
        volumes:
            - postgres-data:/var/lib/postgresql/data
        # Файл содержащий переменные окружения для контейнера
        env_file:
            - .env
        # Используем значения переменных окружения из .env файла
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        # Проверяем готовность сервера и пробуем перезапустить в случае неудачи.
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        tty: true
        stdin_open: true


    nginx:
        # Указываем директорию ./nginx, в которой содержится Dockerfile для сборки образа
        build: ./nginx
        # Пробрасываем 80 порт контейнера на 80 порт локальной машины(порт будет доступен из вне)
        ports:
            - 80:80
        # Примонтируем том static-data к директории /home/app/web/static контейнера nginx
        volumes:
          - static-data:/home/app/web/static
        # Дожидаемся запуска контейнера web
        depends_on:
            - web

    celery:
        build:
            dockerfile: Dockerfile.prod
        command: celery -A megano worker --loglevel=info
        working_dir: /home/app/web
        volumes:
            - ./:/home/app/web
        env_file:
            - .env
        depends_on:
            - db
            - redis

    celery-beat:
        build:
            dockerfile: Dockerfile.prod
        command: celery -A megano beat --loglevel=info
        working_dir: /home/app/web
        volumes:
            - ./:/home/app/web
        env_file:
            - .env
        depends_on:
            - db
            - redis

volumes:
    # Объявляем том postgres-data для хранения данных PostgreSQL
    postgres-data:
    # Объявляем том static-data для хранения статических файлов
    static-data: